<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Category;


class CategoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       // Limpiar la tabla antes de sembrar nuevos datos
       Category::truncate();

       // Datos de ejemplo para las categorías
       $data = [
            ['name' => 'AZUCAR'],
            ['name' => 'ARROZ'],
            ['name' => 'FRIJOL'],
            ['name' => 'MAIZ'],
            ['name' => 'ACEITE COMESTIBLE'],
            ['name' => 'MANTECA'],
            ['name' => 'LECHE INDUSTRIALIZADA'],
            ['name' => 'HARINA DE TRIGO'],
            ['name' => 'HARINA DE MAIZ'],
            ['name' => 'SAL'],
            ['name' => 'TE Y CAFES'],
            ['name' => 'GALLETAS'],
            ['name' => 'PASTAS PARA SOPA'],
            ['name' => 'GRANOS Y SEMILLAS'],
            ['name' => 'ATOLES Y AVENAS'],
            ['name' => 'HARINA PREPARADA Y REPOSTERIA'],
            ['name' => 'ALIMENTOS INFANTILES'],
            ['name' => 'CEREALES INDUSTRIALIZADOS Y SOYA'],
            ['name' => 'CHOCOLATE Y PREPARADOS PARA BEBIDAS'],
            ['name' => 'CAJETA, MERMELADA Y MIEL'],
            ['name' => 'GELATINAS, FLANES Y POSTRES'],
            ['name' => 'FRUTAS ENVASADAS'],
            ['name' => 'JUGOS Y NECTARES'],
            ['name' => 'CONCENTRADOS PARA BEBIDAS'],
            ['name' => 'PESCADOS Y MARISCOS ENLATADOS'],
            ['name' => 'COMIDAS PREPARADAS'],
            ['name' => 'CALDOS Y CONCENTRADOS PARA SOPA'],
            ['name' => 'VEGETALES ENVASADOS'],
            ['name' => 'SALSAS Y PURES'],
            ['name' => 'ACEITUNAS Y VERDURAS ENCURTIDAS'],
            ['name' => 'MAYONESAS, MOSTAZAS Y ADEREZOS'],
            ['name' => 'CHILES ENLATADOS'],
            ['name' => 'MOLES, ADOBOS Y CHILES SECOS'],
            ['name' => 'ANALGESICOS Y MEDICAMENTOS'],
            ['name' => 'CIGARROS Y CERILLOS'],
            ['name' => 'DETERGENTES'],
            ['name' => 'JABON DE LAVANDERIA'],
            ['name' => 'BLANQUEADORES Y SUAVIZANTES'],
            ['name' => 'INSECT. RATICID. DESINF. AROMATIZ.'],
            ['name' => 'LIMPIADORES LIQUIDOS Y EN POLVO'],
            ['name' => 'PANUELOS FACIALES'],
            ['name' => 'PAPEL HIGIENICO'],
            ['name' => 'SERVILLETAS Y TOALLAS'],
            ['name' => 'PLATOS, CUBIERTOS Y VASOS DESECHABLES'],
            ['name' => 'PAPEL, ENVOLTURA Y BOLSAS'],
            ['name' => 'PANALES DESECHABLES'],
            ['name' => 'CREMAS Y CEPILLOS DENTALES'],
            ['name' => 'ALCOHOL'],
            ['name' => 'ALGODON'],
            ['name' => 'ARTICULOS PARA CURACION'],
            ['name' => 'TOALLAS SANITARIAS'],
            ['name' => 'UTENSILIOS DE ALUMINIO Y ACERO'],
            ['name' => 'UTENSILIOS DE LOZA Y PELTRE'],
            ['name' => 'UTENSILIOS DE PLASTICO'],
            ['name' => 'UTENSILIOS DE LAMINA GALVANIZADA'],
            ['name' => 'ESCOBAS, TRAPEADORES Y FIBRAS'],
            ['name' => 'FOCOS Y MATERIAL ELECTRICO'],
            ['name' => 'PILAS Y LINTERNAS'],
            ['name' => 'DESODORANTES, TALCOS Y COSMETICOS'],
            ['name' => 'PERFUMERIA PARA BEBE'],
            ['name' => 'ARTICULOS PARA BEBE'],
            ['name' => 'JABONES DE TOCADOR'],
            ['name' => 'SHAMPOO, ENJUAGUES Y FIJADORES'],
            ['name' => 'CREMA PARA MANOS Y CARA'],
            ['name' => 'ACCESORIOS PARA USO PERSONAL'],
            ['name' => 'PRODUCTOS DE CALZADO'],
            ['name' => 'POSTRES'],
            ['name' => 'CAJAS DE CARTON'],
            ['name' => 'PRODUTOS PARA MASCOTA'],
            ['name' => 'POLVOS PARA HORNEAR'],
            ['name' => 'PRESERVATIVOS'],
            ['name' => 'PRODUCTOS DE LIMPIEZA'],
            ['name' => 'MODIFICADORES DE LECHE'],
            ['name' => 'MEDIAS Y PANTIMEDIAS'],
            ['name' => 'ARTICULOS FOTOGRAFICOS'],
            ['name' => 'ANTISEPTICOS'],
            ['name' => 'ADEREZOS'],
            ['name' => 'BRONCEADORES Y BLOQUEADORES'],
            ['name' => 'CONSOMES'],
            ['name' => 'CONTROL DE PLAGAS'],
            ['name' => 'CARBON PARA EL HOGAR'],
            ['name' => 'GASOLINA'],
            ['name' => 'FRUTAS EN CONSERVA'],
            ['name' => 'MIEL'],
            ['name' => 'COMIDAD PARA LEVAR'],
            ['name' => 'ROPA'],
            ['name' => 'SACHICHONERIA'],
            ['name' => 'PESCADOS Y MARISCOS EN CONSERVA'],
            ['name' => 'TORTILLERIA'],
            ['name' => 'FLORES'],
            ['name' => 'DESAYUNOS Y POSTRES'],
            ['name' => 'CARNES'],
            ['name' => 'BIENES DE USO DURARERO'],
            ['name' => 'VAJILLAS'],
            ['name' => 'SARTENES'],
            ['name' => 'ESPATULAS'],
            ['name' => 'TABLAS PARA CORTAR'],
            ['name' => 'VERDURAS CONGELADAS'],
            ['name' => 'MATERIALES PARA MOTOS'],
            ['name' => 'REFACCIONES'],
            ['name' => 'CARNES ENVASADAS'],
            ['name' => 'DULCES Y CARAMELOS'],
            ['name' => 'ESPECIAS Y CONDIMENTOS'],
            ['name' => 'APLICADORES Y GRASA PARA CALZADO'],
            ['name' => 'VELAS Y VELADORAS'],
            ['name' => 'FERRETERIA Y ACCESORIOS'],
            ['name' => 'CALZADO'],
            ['name' => 'ALIMENTO PECUARIO'],
            ['name' => 'MATERIALES DE CONSTRUCCION'],
            ['name' => 'LOCIONES Y COLONIAS'],
            ['name' => 'PAN'],
            ['name' => 'FERTILIZANTES'],
            ['name' => 'AGUA Y REFRESCOS EMBOTELLADOS'],
            ['name' => 'LIQUIDOS EMBOTELLADOS'],
            ['name' => 'ROPA'],
            ['name' => 'ARTICULOS ESCOLARES'],
            ['name' => 'DESAYUNOS'],
            ['name' => 'HUEVO'],
            ['name' => 'COMPLEMENTOS ALIMENTICIOS SEC SALUD'],
            ['name' => 'PRODUCTOS DE MERCERIA'],
            ['name' => 'TARJETAS TELEFONICAS'],
            ['name' => 'BUZONES Y ESTAMPILLAS POSTALES'],
            ['name' => 'BOLSAS PARA BASURA'],
            ['name' => 'EQUIPO Y HERRAMIENTA TECNOLOGICA'],
            ['name' => 'ENVASES'],
            ['name' => 'VINOS Y LICORES'],
            ['name' => 'ALIMENTO PARA PERRO'],
            ['name' => 'TOSTADAS, TORTILLAS'],
            ['name' => 'LACTEOS ENVAZADOS, REFRIGERADOS'],
            ['name' => 'ARTICULOS VARIOS'],
            ['name' => 'PRODUCTOS DE GAMESA'],
            ['name' => 'PRODUCTOS DE BIMBO'],
            ['name' => 'PRODUCTOS DE MARINELA'],
            ['name' => 'PRODUCTOS DE SABRITAS'],
            ['name' => 'ARTICULOS PARA COMPUTADORA'],
            ['name' => 'PRODUCTOS COCA COLA'],
            ['name' => 'FRITURAS'],
            ['name' => 'CHICLES'],
            ['name' => 'CARAMELOS'],
            ['name' => 'BOMBONES'],
            ['name' => 'PALETAS'],
            ['name' => 'ARTICULOS PARA FIESTA'],
            ['name' => 'DESECHABLES'],
            ['name' => 'BARCEL VARIOS'],
            ['name' => 'CHOCOLATES'],
            ['name' => 'PIÑATAS'],
            ['name' => 'GALLETAS'],
            ['name' => 'GOMITAS'],
            ['name' => 'POLVOS PICANTES'],
            ['name' => 'CACAHUATES'],
            ['name' => 'ARTICULOS INFANTILES'],
            ['name' => 'BOMBON CUBIERTO DE CHOCOLATE'],
            ['name' => 'DULCES DE TAMARINDO'],
            ['name' => 'CHICLOSOS'],
            ['name' => 'BARRAS DE COCO'],
            ['name' => 'GALLETA CUBIERTA CON CHOCOLATE'],
            ['name' => 'PIÑATEROS'],
            ['name' => 'BOLSAS DE CELOFAN'],
            ['name' => 'OBLEAS COL'],
            ['name' => 'PIÑATAS'],
            ['name' => 'PASTAS PARA FRIR'],
            ['name' => 'GLOBOS'],
            ['name' => 'PELOTAS'],
            ['name' => 'CUETES DE POLVORA'],
            ['name' => 'JUGUETES'],
            ['name' => 'BOTANAS Y PAPAS'],
            ['name' => 'PIÃ‘ATEROS'],
            ['name' => 'PRODUCTOS P/CONGELAR'],
            ['name' => 'SEMILLAS'],
            ['name' => 'TEMPORADA'],
            ['name' => 'TEMPORADA MUERTOS'],
            ['name' => 'OCUPAR...'],
            ['name' => 'CONFETTI'],
            ['name' => 'VASOS DESECHABLES'],
            ['name' => 'CARAMELO LIQUIDO'],
            ['name' => 'PALOS Y PALILLOS'],
            ['name' => 'BOLSAS DULCERAS'],
            ['name' => 'INVITACIONES'],
            ['name' => 'CAJAS DULCERAS'],
            ['name' => 'COHETES'],
            ['name' => 'CHILE EN POLVO'],
            ['name' => 'GORROS..'],
            ['name' => 'CHILES POLVO'],
            ['name' => 'JUEGOS DIDACTICOS'],
            ['name' => 'LETRERO FIESTA'],
            ['name' => 'CORTINAS FIESTA'],
            ['name' => 'CUBREBOCAS'],
            ['name' => 'BOLSA DE REGALO'],
            ['name' => 'PAPELERIA'],
            ['name' => 'LLAVERO'],
            ['name' => 'TEMP 14 FEB'],
            ['name' => 'SLIME PIEZA'],
           // Puedes agregar más categorías según tus necesidades
       ];

       // Sembrar los datos en la tabla de categorías
       Category::insert($data);

    }
}
